apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'while true; do date >> /data/timestamps.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /data
      name: hostpath-volume
  - name: busybox2
    image: busybox
    command: ['sh', '-c', 'tail -f /shared-data/timestamps.txt']
    volumeMounts:
    - mountPath: /shared-data
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /var/data
      type: DirectoryOrCreate