apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo-pod
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'while true; do date >> /data/timestamps.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /data
      name: pvc-volume
  - name: busybox2
    image: busybox
    command: ['sh', '-c', 'tail -f /shared-data/timestamps.txt']
    volumeMounts:
    - mountPath: /shared-data
      name: pvc-volume
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: pvc-demo