apiVersion: batch/v1
kind: CronJob
metadata:
  name: ku-cron-job
  labels:
    target: job
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ku-cron-job
            target: job
        spec:
          containers:
            - name: kubia
              image: luksa/batch-job
          restartPolicy: OnFailure
