apiVersion: batch/v1
kind: Job
metadata:
  name: ku-job
  labels:
    target: job
spec:
  template:
    metadata:
      labels:
        app: ku
        target: job
    spec:
      containers:
        - name: kubia
          image: luksa/batch-job
      restartPolicy: OnFailure
