apiVersion: batch/v1
kind: Job
metadata:
  name: ku-multi-completion-parallel-job
  labels:
    target: job
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: ku-multi-completion-parallel-job
        target: job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ku-multi-completion-parallel-job
          image: luksa/batch-job
