apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ku-lb-rs-2
  labels:
    target: svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ku-lb-2
      target: svc
  template:
    metadata:
      labels:
        app: ku-lb-2
        target: svc
    spec:
      containers:
        - name: ku
          image: luksa/kubia
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ku-load-balancer-service-2
  labels:
    target: svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ku-lb-2
    target: svc
