apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ku-rs
  labels:
    target: svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ku
      target: svc
  template:
    metadata:
      labels:
        app: ku
        target: svc
    spec:
      containers:
        - name: ku
          image: luksa/kubia
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ku-load-balancer-service
  labels:
    target: svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ku
    target: svc
