apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ku-rs
  labels:
    target: svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ku
      target: svc
  template:
    metadata:
      labels:
        app: ku
        target: svc
    spec:
      containers:
        - name: ku
          image: luksa/kubia
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ku-node-port-service
  labels:
    target: svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30123
  selector:
    app: ku
