apiVersion: v1
kind: Service
metadata:
  name: ku-svc
  labels:
    target: svc
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ku
    target: svc
---
apiVersion: v1
kind: Pod
metadata:
  name: ku-pod
  labels:
    app: ku
    target: svc
spec:
  containers:
    - name: kubia
      image: luksa/kubia
      ports:
        - containerPort: 8080
