apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ku-pool
  namespace: metallb-system
  labels:
    target: rc
spec:
  addresses:
    - 192.168.10.0/24
    - 192.168.9.1-192.168.9.5
    - fc00:f853:0ccd:e799::/124
