apiVersion: batch/v1
kind: Job
metadata:
  name: ku-job
  labels:
    target: rc
spec:
  template:
    metadata:
      labels:
        app: ku
        target: rc
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            exec:
              command:
                - ls
                - /var/ready
