apiVersion: batch/v1
kind: Job
metadata:
  name: ku-multi-completion-job
  labels:
    target: rc
spec:
  completions: 5
  template:
    metadata:
      labels:
        app: ku-multi-completion-job
        target: rc
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ku-multi-completion-job
          image: luksa/batch-job
