apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ku-rs
  labels:
    target: rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ku
      target: rc
  template:
    metadata:
      labels:
        app: ku
        target: rc
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
            - containerPort: 8080
