apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: ku-rc
  labels:
    target: rc
spec:
  replicas: 2
  selector:
    app: ku
  template:
    metadata:
      labels:
        app: ku
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
            - containerPort: 8080
