apiVersion: v1
kind: Service
metadata:
  name: ku-loadbalancer
  labels:
    target: rc
  annotations:
    metallb.universe.tf/address-pool: ku-pool
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ku
