apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config-map-as-env
  labels:
    target: conf
data:
  NAME: "IRON_MAN"
  AGE: "40"
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-config-map-as-env-pod
  labels:
    target: conf
spec:
  containers:
  - name: demo-config-map-as-env-container
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - configMapRef:
        name: demo-config-map-as-env