apiVersion: v1
kind: Secret
metadata:
  name: secret-with-data
  labels:
    target: conf
data:
  username: YWRtaW4=
  password: MTIzNDU2
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-with-data-pod
  labels:
    target: conf
spec:
  containers:
  - name: secret-with-data-container
    image: busybox
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: insecure-secret