apiVersion: v1
kind: Secret
metadata:
  name: secret-with-string-data
  labels:
    target: conf
stringData:
  username: "admin"
  password: "123456"
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-with-string-data-pod
  labels:
    target: conf
spec:
  containers:
  - name: secret-with-string-data-container
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-with-string-data
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-with-string-data
          key: password