apiVersion: v1
kind: Secret
metadata:
  name: secret-as-file
  labels:
    target: conf
data:
  username: YWRtaW4=
  password: MTIzNDU2
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-as-file-pod
  labels:
    target: conf
spec:
  containers:
  - name: secret-as-file-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-as-file