apiVersion: v1
kind: Pod
metadata:
  name: pod-label
  labels:
    target: pod
    env: prod
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
